#! /usr/bin/env bash

__APMS=(
atom-beautify
atom-ternjs
autoclose-html
busy-signal
color-picker
editorconfig
file-icons
go-plus
highlight-selected
language-docker
language-markdown
language-protobuf
markdown-scroll-sync
markdown-toc
monokai-seti
platformio-ide-terminal
pigments
seti-ui
seti-syntax
Stylus
language-markdown
)

for i in ${__APMS[@]};do
  apm install $i
done

#atom-live-server
#autocomplete-go
#autocomplete-html-entities
#atom-autocomplete-php
#auto-detect-indentation
#atom-uikit
#autocomplete-modules
#autocomplete-swift
#builder-go
#ember-snippets
#go-config
#gometalinter-linter
#go-plus
#html-productivity
#hyperclick
#intentions
#language-babel
#language-javascript-jsx
#language-php
#language-swift
#language-viml
#language-vue
#language-vue-component
#linter
#linter-ui-default
#linter-eslint
#markdown-preview-plus
#markdown-scroll-sync
#markdown-toc
#meteor-helper
#navigator-godef
#pandoc-convert
#particle-dev-complete
#php-integrator-autocomplete-plus
#php-integrator-base
#php-integrator-navigation
#prettier-atom
#react-es6-snippets
#react-snippets
#seti-syntax
#seti-ui
#snippet-generator
#swift-debugger
#tester-go
#tool-bar
#tool-bar-main
#vue-autocomplete
#vue-snippets
